### create a new patient entity
# REST CLIENT
# POST http://localhost:4000/patients

# API-GATEWAY
POST http://localhost:4004/api/patients
Content-Type: application/json

{
    "name" : "John Joe with api",
    "email" : "test_api_gateway@exapmle.com",
    "address" : "123 main street",
    "dateOfBirth" : "1995-09-09",
    "registeredDate" : "2025-05-15"
}
###