### upadates existing patient entity
# REST CLIENT
# PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000

# API-GATEWAY
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
    "name" : "John Joe Updated 1",
    "email" : "john.doe@example.com",
    "address" : "123 ain street",
    "dateOfBirth" : "1995-09-09"

}

###